services:
  - type: web
    name: stock-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
